<?php
$escape = $this->plugin('escapeHtml');
$resourceMedia = $resource->media();
$decoration = $this->themeSetting('image_decoration');
?>
<?php if ($resourceMedia): ?>
<dl class="media-list">
    <div class="property">
        <dt><?php echo $this->translate('Media'); ?></dt>
        <?php foreach ($resourceMedia as $media): ?>
            <?php
            $altText = $media->altText() ?: $media->displayTitle() ?: '';
            $thumbnail = $this->thumbnail($media, 'square', ['alt' => $altText]);
            $mediaType = (string) $media->mediaType();
            $linkContent = sprintf('%s<span class="resource-name">%s</span>',
                $thumbnail,
                $escape($media->displayTitle())
            );
            ?>
            <dd class="value <?php echo is_array($decoration) && in_array('media', $decoration) ? 'decoration decoration--thumbnail' : ''; ?>">
                <?php echo $media->linkRaw($linkContent, null, ['class' => 'resource-link', 'target' => '_blank', 'rel' => 'noopener', 'data-media-type' => $mediaType, 'data-is-pdf-media' => $mediaType === 'application/pdf' ? '1' : '0']); ?>
            </dd>
        <?php endforeach; ?>
    </div>
</dl>
<?php endif; ?>
